// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aorpjttyeulrzitvpjkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvcnBqdHR5ZXVscnppdHZwamtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODY4NDQsImV4cCI6MjA2NTY2Mjg0NH0.QSUGQVXPanPSNmby_rGp02CUrkegmACewiNRzug2088";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);